---
title: "02-dge"
output: html_document
date: "2023-04-04"
---


# Getting the data

There is data on a public server. In the given directory here are all the files present.


```







noting here is what I want

|               |          |
|---------------|----------|
| Sample        | SampleID |
| D-control     | D54      |
| D-control     | D55      |
| D-control     | D56      |
| D-control     | D57      |
| D-control     | D58      |
| D-control     | D59      |
| D-control     | M45      |
| D-control     | M46      |
| D-control     | M48      |
| D-control     | M49      |
| D-control     | M89      |
| D-control     | M90      |
| D-desiccation | N48      |
| D-desiccation | N49      |
| D-desiccation | N50      |
| D-desiccation | N51      |
| D-desiccation | N52      |
| D-desiccation | N53      |
| D-desiccation | N54      |
| D-desiccation | N55      |
| D-desiccation | N56      |
| D-desiccation | N57      |
| D-desiccation | N58      |
| D-desiccation | N59      |


the files are in on this public server 
https://gannet.fish.washington.edu/seashell/bu-github/nb-2023/Cgigas/data/nopp/

md5 hashses

```
05a40698730c7676356113f97fdadcba  D54_S145_L001_R1_001.fastq.gz
3caf3dbf16a4a2a77d29ccb83766c63d  D55_S146_L001_R1_001.fastq.gz
f4dac6c88b994a5cc2e983dec1b7709c  D56_S136_L001_R1_001.fastq.gz
b15981c0682ea7354d302ab20d502334  D57_S143_L001_R1_001.fastq.gz
16ccdb13c270da4368d75e1784f13717  D58_S144_L001_R1_001.fastq.gz
01dd7a84ebd6101e30f771e4d543a542  D59_S142_L001_R1_001.fastq.gz
a9289891391adcbf9de94cbd7c5922ec  M45_S140_L001_R1_001.fastq.gz
327fa9c520ff28d7bd38dda8fb4bcf69  M46_S141_L001_R1_001.fastq.gz
0466373a6edc9d801ad9b77cc774832d  M48_S137_L001_R1_001.fastq.gz
b0a202e20dc1005e969672be4c94c36d  M49_S139_L001_R1_001.fastq.gz
d5ad2ac754993da2a49df005d52aee54  M89_S138_L001_R1_001.fastq.gz
431ee553d21052ee05db4de81214b04b  M90_S147_L001_R1_001.fastq.gz
ec4d26b09a68ba7a12a83e07bde5abcc  N48_S194_L001_R1_001.fastq.gz
2480da7ac05b2cdb6384ddeb9768c04e  N49_S185_L001_R1_001.fastq.gz
deef78829c8552f9092996ea90d95385  N50_S187_L001_R1_001.fastq.gz
80991c2ff7996133778392989279a7ce  N51_S186_L001_R1_001.fastq.gz
57c825f3c3a7eb95b40e15c5d344cc82  N52_S184_L001_R1_001.fastq.gz
263516685fffc25465af0ba42f9b4ebb  N53_S188_L001_R1_001.fastq.gz
a51351eeaf3a7bc8eb33e8e9a2ac63ba  N54_S193_L001_R1_001.fastq.gz
865e49e1ec2811557cf9bc205c6af396  N55_S190_L001_R1_001.fastq.gz
5a5e7d98e6fd311a3c2e9f679cba17cd  N56_S192_L001_R1_001.fastq.gz
5784e6e05ecea31c9019e24d8ff2a440  N57_S191_L001_R1_001.fastq.gz
fd82abdd214f6eff233dfa0e03da287e  N58_S195_L001_R1_001.fastq.gz
591a83ef2a0eab99a50a5e3ad4b705aa  N59_S189_L001_R1_001.fastq.gz
```


```{bash}
cd ../data 
wget --recursive --no-parent --no-directories \
--no-check-certificate \
--accept '[DMN]*001.fastq.gz' \
https://gannet.fish.washington.edu/seashell/bu-github/nb-2023/Cgigas/data/nopp/
```



```{bash}
/home/shared/kallisto/kallisto -h
```

```{bash}
cd ../data
curl -O https://gannet.fish.washington.edu/seashell/bu-github/nb-2023/Cgigas/data/rna.fna
```


```{bash}
/home/shared/kallisto/kallisto \
index -i \
../data/cgigas_roslin_rna.index \
/home/shared/8TB_HDD_01/sr320/github/nb-2023/Cgigas/data/rna.fna
```


N59_S189_L002_R1_001.fastq.gz

```{bash}
/home/shared/kallisto/kallisto \
quant -i ../data/cgigas_roslin_rna.index \
-o ../output/kallisto_01/N59 \
-t 40 \
--single -l 100 -s 10 /home/shared/8TB_HDD_01/sr320/github/nb-2023/Cgigas/data/N59_S189_L002_R1_001.fastq.gz
```


```{bash}
find /home/shared/8TB_HDD_01/sr320/github/nb-2023/Cgigas/data/*_L001_R1_001.fastq.gz \
| xargs basename -s _L001_R1_001.fastq.gz | xargs -I{} /home/shared/kallisto/kallisto \
quant -i ../data/cgigas_roslin_rna.index \
-o ../output/kallisto_01/{} \
-t 40 \
--single -l 100 -s 10 /home/shared/8TB_HDD_01/sr320/github/nb-2023/Cgigas/data/{}_L001_R1_001.fastq.gz
```


